config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  mount ActionCable.server => '/cable'

  get '/teacher-dashboard', to: 'dashboard#teacher', as: :teacher_dashboard
  get '/student-dashboard', to: 'dashboard#student', as: :student_dashboard

  get '/dashboard/change-class/:id', to: 'dashboard#change_class', as: :change_class
  get '/students/leaderboard', to: 'students#leaderboard', as: :students_leaderboard

  get '/assignments/:id/cancel', to: 'assignments#cancel', as: :cancel_assignment

  post '/dashboard/get-tracks', to: 'dashboard#get_tracks', as: :ajax_tracks
  post '/dashboard/get-code-lessons', to: 'dashboard#get_code_lessons', as: :ajax_code_lessons
  post '/dashboard/get-students', to: 'dashboard#get_students', as: :ajax_students

  get '/assignments/old-assignments/:id', to: 'assignments#old_assignments', as: :student_old_assignments

  get '/code-lessons/:code_lesson_id/submissions/:student_id', to: 'submissions#student_submissions', as: :student_lesson_submissions
  get 'submissions/:id', to: 'submissions#show', as: :submission

  get '/insights/course/:id', to: 'insights#course', as: :course_insights
  get '/insights/track/:id', to: 'insights#track', as: :track_insights
  get '/insights/student/:id', to: 'insights#student', as: :student_insights
  get '/insights/code_lesson/:id', to: 'insights#code_lesson', as: :code_lesson_insights
  post '/insights/get-course-submissions', to: 'insights#get_course_submissions', as: :ajax_course_submissions
  post '/insights/get-track-submissions', to: 'insights#get_track_submissions', as: :ajax_track_submissions
  post '/insights/get-code-lesson-submissions', to: 'insights#get_code_lesson_submissions', as: :ajax_code_lesson_submissions
  post '/insights/get-student-submissions', to: 'insights#get_student_submissions', as: :ajax_students_submissions
  post '/insights/get-student-time-spent', to: 'insights#get_student_time_spent', as: :ajax_students_time_spent


  resources :organisation_classes, path: 'classes'

  get '/classes/:id/courses', to: 'organisation_classes#courses', as: :organisation_class_courses
  post '/courses/:course_id/assign-to-classes', to: 'courses#assign_to_classes', as: :assign_course_to_classes

  resources :courses, shallow: true do
    resources :tracks do
      resources :code_lessons, path: 'code-lessons' do
        resources :submissions
      end
    end
  end

  post '/code-lessons/:id/run-code', to: 'code_lessons#run_code', as: :run_code
  post '/code-lessons/:id/get-hint', to: 'code_lessons#get_hint', as: :get_hint
  post '/code-lessons/:id/get-starting-code', to: 'code_lessons#get_starting_code', as: :get_starting_code
  post '/code-lessons/:id/get-next-lesson', to: 'code_lessons#get_next_lesson', as: :get_next_lesson
  get '/code-lessons/:code_lesson_id/chat/:chat_id', to: 'code_lessons#chat', as: :code_lesson_chat

  get '/library', to: 'course_templates#index', as: :course_templates
  post '/library', to: 'course_templates#create'
  post '/course-templates/:course_template_id/add-to-organisation', to: 'course_templates#add_to_organisation', as: :add_course_template_to_organisation

  resources :course_templates, path: 'course-templates', shallow: true, except: :index do
    resources :track_templates, path: 'track-templates' do
      resources :code_lesson_templates, path: 'code-lesson-templates'
    end
  end

  resources :chat_messages do
    resources :chats
  end

  resources :live_coding_sessions, path: 'live-coding-sessions'
  get '/live-coding-sessions/:id/resolve', to: 'live_coding_sessions#resolve', as: :resolve_live_coding_session
  post '/live-coding-sessions/:live_coding_session_id/publish-code', to: 'live_coding_sessions#publish_code', as: :live_coding_session_publish_code

  get '/students/:id/get-assignments', to: 'students#get_assignments', as: :student_get_assignments

  get '/students/new', to: 'students#new', as: :new_student
  post '/students', to: 'students#create'

  devise_for :admins, skip: [:registrations]
  devise_for :teachers
  devise_for :students
  resources :students, only: [:index, :show, :edit, :destroy, :update]

end

app/controllers/organisation_classes_controller.rb
class OrganisationClassesController < ApplicationController
  before_action :set_organisation_class, only: [:show, :edit, :update, :destroy, :courses]
  before_action :authenticate_teacher!, only: [:new, :create, :edit, :update, :destroy]

  # GET /organisation_classes
  # GET /organisation_classes.json
  def index
    @organisation_classes = OrganisationClass.all
  end

  # GET /organisation_classes/1
  # GET /organisation_classes/1.json
  def show
  end

  # GET /organisation_classes/new
  def new
    @organisation_class = OrganisationClass.new
  end

  # GET /organisation_classes/1/edit
  def edit
  end

  # POST /organisation_classes
  # POST /organisation_classes.json
  def create
    @organisation_class = current_teacher.organisation_classes.build(organisation_class_params)

    respond_to do |format|
      if @organisation_class.save
        current_teacher.teachers_classes.create({
          teacher_id: current_teacher.id,
          organisation_class_id: @organisation_class.id
        })
        format.html { redirect_to @organisation_class, notice: 'Organisation class was successfully created.' }
        format.json { render :show, status: :created, location: @organisation_class }
      else
        format.html { render :new }
        format.json { render json: @organisation_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisation_classes/1
  # PATCH/PUT /organisation_classes/1.json
  def update
    respond_to do |format|
      if @organisation_class.update(organisation_class_params)
        format.html { redirect_to @organisation_class, notice: 'Organisation class was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation_class }
      else
        format.html { render :edit }
        format.json { render json: @organisation_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisation_classes/1
  # DELETE /organisation_classes/1.json
  def destroy
    @organisation_class.destroy
    respond_to do |format|
      format.html { redirect_to organisation_classes_url, notice: 'Organisation class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def courses
    @courses = @organisation_class.courses
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation_class
      @organisation_class = OrganisationClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisation_class_params
      params.require(:organisation_class).permit(:name, :code, :organisation_id)
    end
end

app/helpers/organisation_classes_helper.rb
module OrganisationClassesHelper
end

app/views/organisation_classes/_form.html.erb
<%= form_with(model: organisation_class, local: true) do |form| %>
  <% if organisation_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation_class.errors.count, "error") %> prohibited this organisation_class from being saved:</h2>

      <ul>
      <% organisation_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name%>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= form.label :code%>
    <%= form.text_field :code, class: "form-control" %>
  </div>

  <%= form.hidden_field :organisation_id, value: current_teacher.organisation_id %>

  <div class="actions row">
    <%= form.submit 'Create Class', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/organisation_classes/courses.html.erb
<h1 class="text-center header-padding"><%= @organisation_class.long_name %></h1>

<% if !@courses.any? %>
  <div class="nothinghere">
    No Courses Here
  </div>
<% end %>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col-md-4">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title"><%= link_to course.name, course %></h5>
          <p class="card-text"><%= course.description %></p>
        </div>
        <% if teacher_signed_in? %>
          <div class="card-footer text-muted">
            <%= link_to 'Assign to Students', '#', class: 'btn btn-primary open-target-modal', data: { target: "assign_students_course_modal_#{course.id}" } %>
          </div>
        <% end %>
      </div>
      </br>
    </div>
  <% end %>
</div>

<% @courses.each do |course| %>
  <div class="modal fade" id="assign_students_course_modal_<%= course.id %>" tabindex="-1" role="dialog" aria-labelledby="new_code_lesson_modal_title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <%= form_tag(assign_course_to_classes_path(course)) do %>
          <div class="modal-header">
            <h5 class="modal-title" id="new_code_lesson_modal_title">Assing <%= course.name %> as homework to a class</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="form-group">
              Assign to class:

              <div class="form-control">
                <% course.organisation_classes.each do |org_class| %>
                  <div class="form-check">
                    <%= check_box_tag "organisation_classes[#{course.id}][#{org_class.id}]", 1, false, class: 'form-check-input' %>
                    <label for="organisation_classes_<%= course.id %>_<%= org_class.id %>" class="form-check-label">
                      <%= org_class.name %>
                    </label>
                  </div>
                <% end %>
              </div>

              <div class="form-group">
                <label>Date start</label>
                <div class="form-control">
                  <%= datetime_select 'assignment', 'date_start' %>
                </div>
              </div>

              <div class="form-group">
                <label>Date due</label>
                <div class="form-control">
                  <%= datetime_select 'assignment', 'date_due' %>
                </div>
              </div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= submit_tag 'Assign to Class', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/organisation_classes/edit.html.erb
<h1>Editing Organisation Class</h1>

<%= render 'form', organisation_class: @organisation_class %>

<%= link_to 'Show', @organisation_class %> |
<%= link_to 'Back', organisation_classes_path %>

app/views/organisation_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organisation Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Organisation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisation_classes.each do |organisation_class| %>
      <tr>
        <td><%= organisation_class.name %></td>
        <td><%= organisation_class.code %></td>
        <td><%= organisation_class.organisation_id %></td>
        <td><%= link_to 'Show', organisation_class %></td>
        <td><%= link_to 'Edit', edit_organisation_class_path(organisation_class) %></td>
        <td><%= link_to 'Destroy', organisation_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisation Class', new_organisation_class_path %>

app/views/organisation_classes/new.html.erb
<h1 class="display-4 row">New Class</h1>

<%= render 'form', organisation_class: @organisation_class %>

app/views/organisation_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organisation_class.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @organisation_class.code %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @organisation_class.organisation_id %>
</p>

<%= link_to 'Edit', edit_organisation_class_path(@organisation_class) %> |
<%= link_to 'Back', organisation_classes_path %>