config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  mount ActionCable.server => '/cable'

  get '/teacher-dashboard', to: 'dashboard#teacher', as: :teacher_dashboard
  get '/student-dashboard', to: 'dashboard#student', as: :student_dashboard

  get '/dashboard/change-class/:id', to: 'dashboard#change_class', as: :change_class
  get '/students/leaderboard', to: 'students#leaderboard', as: :students_leaderboard

  get '/assignments/:id/cancel', to: 'assignments#cancel', as: :cancel_assignment

  post '/dashboard/get-tracks', to: 'dashboard#get_tracks', as: :ajax_tracks
  post '/dashboard/get-code-lessons', to: 'dashboard#get_code_lessons', as: :ajax_code_lessons
  post '/dashboard/get-students', to: 'dashboard#get_students', as: :ajax_students

  get '/assignments/old-assignments/:id', to: 'assignments#old_assignments', as: :student_old_assignments

  get '/code-lessons/:code_lesson_id/submissions/:student_id', to: 'submissions#student_submissions', as: :student_lesson_submissions
  get 'submissions/:id', to: 'submissions#show', as: :submission

  get '/insights/course/:id', to: 'insights#course', as: :course_insights
  get '/insights/track/:id', to: 'insights#track', as: :track_insights
  get '/insights/student/:id', to: 'insights#student', as: :student_insights
  get '/insights/code_lesson/:id', to: 'insights#code_lesson', as: :code_lesson_insights
  post '/insights/get-course-submissions', to: 'insights#get_course_submissions', as: :ajax_course_submissions
  post '/insights/get-track-submissions', to: 'insights#get_track_submissions', as: :ajax_track_submissions
  post '/insights/get-code-lesson-submissions', to: 'insights#get_code_lesson_submissions', as: :ajax_code_lesson_submissions
  post '/insights/get-student-submissions', to: 'insights#get_student_submissions', as: :ajax_students_submissions
  post '/insights/get-student-time-spent', to: 'insights#get_student_time_spent', as: :ajax_students_time_spent


  resources :organisation_classes, path: 'classes'

  get '/classes/:id/courses', to: 'organisation_classes#courses', as: :organisation_class_courses
  post '/courses/:course_id/assign-to-classes', to: 'courses#assign_to_classes', as: :assign_course_to_classes

  resources :courses, shallow: true do
    resources :tracks do
      resources :code_lessons, path: 'code-lessons' do
        resources :submissions
      end
    end
  end

  post '/code-lessons/:id/run-code', to: 'code_lessons#run_code', as: :run_code
  post '/code-lessons/:id/get-hint', to: 'code_lessons#get_hint', as: :get_hint
  post '/code-lessons/:id/get-starting-code', to: 'code_lessons#get_starting_code', as: :get_starting_code
  post '/code-lessons/:id/get-next-lesson', to: 'code_lessons#get_next_lesson', as: :get_next_lesson
  get '/code-lessons/:code_lesson_id/chat/:chat_id', to: 'code_lessons#chat', as: :code_lesson_chat

  get '/library', to: 'course_templates#index', as: :course_templates
  post '/library', to: 'course_templates#create'
  post '/course-templates/:course_template_id/add-to-organisation', to: 'course_templates#add_to_organisation', as: :add_course_template_to_organisation

  resources :course_templates, path: 'course-templates', shallow: true, except: :index do
    resources :track_templates, path: 'track-templates' do
      resources :code_lesson_templates, path: 'code-lesson-templates'
    end
  end

  resources :chat_messages do
    resources :chats
  end

  resources :live_coding_sessions, path: 'live-coding-sessions'
  get '/live-coding-sessions/:id/resolve', to: 'live_coding_sessions#resolve', as: :resolve_live_coding_session
  post '/live-coding-sessions/:live_coding_session_id/publish-code', to: 'live_coding_sessions#publish_code', as: :live_coding_session_publish_code

  get '/students/:id/get-assignments', to: 'students#get_assignments', as: :student_get_assignments

  get '/students/new', to: 'students#new', as: :new_student
  post '/students', to: 'students#create'

  devise_for :admins, skip: [:registrations]
  devise_for :teachers
  devise_for :students
  resources :students, only: [:index, :show, :edit, :destroy, :update]

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_teacher!, only: :teacher
  before_action :authenticate_student!, only: :student

  def teacher
    @code_lesson = CodeLesson.new
    @chats = Chat.find_all_for_teacher(current_teacher)
  end

  def student
    @submissions = Submission.where(student_id: current_student.id)

    if @submissions.any?
      @sorted = @submissions.order(created_at: :desc)
      @latest = @sorted.first
      @current_code_lesson = @latest.code_lesson
      @current_track = @current_code_lesson.track
      @current_course = @current_track.course
    end

    @assignments = Assignment.where(student_id: current_student.id)
  end

  def change_class
    cookies.permanent[:class_id] = params[:id]
    cookies[:course_id] = nil
    cookies[:track_id] = nil
    cookies[:code_lesson_id] = nil

    if student_signed_in?
      org_class = OrganisationClass.find(cookies[:class_id])
      return redirect_to organisation_class_courses_path(org_class)
    end

    redirect_to teacher_dashboard_path
  end

  def get_tracks
    course = Course.find(params[:course_id])
    cookies[:course_id] = params[:course_id]
    cookies[:track_id] = nil
    cookies[:code_lesson_id] = nil
    return_obj = {
      tracks: course.tracks,
      display_tracks_link: course_tracks_path(course)
    }
    render json: return_obj.to_json.inspect
  end

  def get_code_lessons
    track = Track.find(params[:track_id])
    cookies[:track_id] = params[:track_id]
    cookies[:code_lesson_id] = nil
    return_obj = {
      code_lessons: track.code_lessons.order(:order),
      display_lessons_link: track_code_lessons_path(track),
    }
    render json: return_obj.to_json.inspect
  end

  def get_students
    code_lesson = CodeLesson.find(params[:code_lesson_id])
    org_class = OrganisationClass.find(cookies[:class_id])
    cookies[:code_lesson_id] = params[:code_lesson_id]

    students = org_class.students
    results = []
    num_of_subs = []
    hint_used = []
    students.each do |s|
      all_submissions = s.get_submissions(code_lesson)
      if all_submissions.length == 0
        results << nil
        num_of_subs << 0
        hint_used << false
      else
        result = false
        used_hint = false
        all_submissions.each do |submission|
          result = result || submission.success
          used_hint = used_hint || submission.used_hint
        end
        results << result
        num_of_subs << all_submissions.size
        hint_used << used_hint
      end
    end
    return_obj = {
      students: students,
      results: results,
      num_of_subs: num_of_subs,
      hint_used: hint_used
    }
    render json: return_obj.to_json.inspect
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h2>Class: <%= @current_class.name %></h2>

<div class="row">
  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        Courses
      </div>
      <ul class="list-group list-group-flush dashboard-list-group -courses">
        <% @current_class.courses.each do |course| %>
          <li class="list-group-item dashboard-list-group-item -course <% if course == @current_course %>-selected<% end %>" data-course-id="<%= course.id %>">
            <%= course.name %>
          </li>
          <li class="list-group-item dashboard-list-group-item-info -course" <% unless course == @current_course %>style="display: none;"<% end %>>
            <%= course.description %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        Tracks
      </div>
      <ul class="list-group list-group-flush dashboard-list-group -tracks">
        <% if @current_course %>
          <% @current_course.tracks.each do |track| %>
            <li class="list-group-item dashboard-list-group-item -track <% if track == @current_track %>-selected<% end %>" data-track-id="<%= track.id %>">
              <%= track.name %>
            </li>
            <li class="list-group-item dashboard-list-group-item-info -track" <% unless track == @current_track %>style="display: none;"<% end %>>
              <%= track.description %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        Code Lessons
      </div>
      <ul class="list-group list-group-flush dashboard-list-group -code-lessons">
        <% if @current_track %>
          <% @current_track.code_lessons.each do |code_lesson| %>
            <li class="list-group-item dashboard-list-group-item -code-lesson <% if code_lesson == @current_code_lesson %>-selected<% end %>" data-code-lesson-id="<%= code_lesson.id %>">
              <%= code_lesson.name %>
            </li>
            <li class="list-group-item dashboard-list-group-item-info -code-lesson" <% unless code_lesson == @current_code_lesson %>style="display: none;"<% end %>>
              <%= link_to code_lesson.name, code_lesson %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        Students
      </div>
      <div class="card-body">
        <div class="card border-secondary mb-3" style="max-width: 18rem; padding:10px">
          <h5 class="card-title">Special title treatment</h5>
          <a href="#" class="btn btn-info btn-sm" style="width: auto">insight</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/student.html.erb
<h2 class="display-4"><%= current_student.name %></h2>

<h3 class=>Points: <%= current_student.points %></h3>


<div class="row">
  <% if @submissions.any? && current_student.outstanding_courses.any?%>
    <div class="col-md-8">
      <h3>Current Progress</h3>
      <div class="card text-center">
        <div class="card-header">
          <%= @current_course.name %>
        </div>
        <div class= "row">
          <div class= "col-md-8">
            <div class="card border-secondary">
              <div class="card-header">
                <%= @current_track.name %>
              </div>
              <li class="list-group-item dashboard-list-group-item-info">
                <%= @current_code_lesson.name %>
              </li>
            </div>
          </div>
          <div class= "col-md-4 text-center align-self-center">
            <%= link_to "Continue", @current_code_lesson, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

<h3>Current Assignments</h3>
<div class="row">
  <div class="col-md-12">
    <% if current_student.outstanding_courses.any? %>
      <% current_student.outstanding_courses.each do |course| %>
        <div class="card">
          <div class="card-header">
            <%= course.name %>
            <div class="progress-bar" role="progressbar" style="width: <%= course.progress(current_student) %>%;" aria-valuenow= "<%= course.progress(current_student) %>" aria-valuemin="0" aria-valuemax="100">
              <% if course.progress(current_student) >= 5 %>
                <%= course.progress(current_student)%> %
              <% else %>
                <p> </p>
              <% end %>
            </div>
          </div>
          <ul class="list-group list-group-flush student-dashboard-list-group -track">
            <% course.tracks.each do |track| %>
              <li class="list-group-item student-dashboard-list-group-item -track">
                <%= track.name %>
                <div class="progress-bar" role="progressbar" style="width: <%= track.progress(current_student) %>%;" aria-valuenow= "<%= track.progress(current_student) %>" aria-valuemin="0" aria-valuemax="100">
                  <% if track.progress(current_student) >= 5 %>
                    <%= track.progress(current_student) %> %
                  <% else %>
                    <p> </p>
                  <% end %>
                </div>
              </li>
              <ul class="list-group list-group-flush student-dashboard-list-group-item-info -track" style="display: none;">
                <% track.code_lessons.each do |lesson| %>
                  <li class="list-group-item">
                    <% assignment = lesson.get_assignment_for(current_student) %>
                    <div class="float-right" data-toggle="tooltip" data-placement="top" title="<%= assignment.date_due.strftime("%H:%S %a #{assignment.date_due.day.ordinalize} %b %Y") %>">
                      Due in <%= time_ago_in_words assignment.date_due %>
                    </div>
                    <%= link_to lesson.name, lesson %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% else %>
      <li class="list-group-item">No upcoming assignments</li>
    <% end %>
  </div>
</div>

app/views/dashboard/teacher.html.erb
<h2 class="text-center class-header">Class: <%= @current_class.name %></h2>

<div class="row">
  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        Courses
      </div>
      <ul class="list-group list-group-flush dashboard-list-group -courses">
        <% @current_class.courses.each do |course| %>
          <li class="list-group-item dashboard-list-group-item -course <% if course == @current_course %>-selected<% end %>" data-course-id="<%= course.id %>">
            <%= course.name %>
          </li>
          <li class="list-group-item dashboard-list-group-item-info -course" <% unless course == @current_course %>style="display: none;"<% end %>>
            <div class="btn-group btn-group-sm">
              <%= link_to "Insights", course_insights_path(course), class: 'btn btn-secondary' %>
            </div>
          </li>
        <% end %>
        <li class="list-group-item dashboard-list-group-item"><%= link_to 'Manage courses', organisation_class_courses_path(@current_class) %></li>
      </ul>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        Tracks
      </div>
      <ul class="list-group list-group-flush dashboard-list-group -tracks">
        <% if @current_course %>
          <% @current_course.tracks.each do |track| %>
            <li class="list-group-item dashboard-list-group-item -track <% if track == @current_track %>-selected<% end %>" data-track-id="<%= track.id %>">
              <%= track.name %>
            </li>
            <li class="list-group-item dashboard-list-group-item-info -track" <% unless track == @current_track %>style="display: none;"<% end %>>
              <div class="btn-group btn-group-sm">
                <%= link_to "Insights", track_insights_path(track), class: 'btn btn-secondary' %>
              </div>
            </li>
          <% end %>
          <li class="list-group-item dashboard-list-group-item"><%= link_to 'Manage tracks', course_tracks_path(@current_course) %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        Code Lessons
      </div>
      <ul class="list-group list-group-flush dashboard-list-group -code-lessons">
        <% if @current_track %>
          <% @current_track.code_lessons.order(:order).each do |code_lesson| %>
            <li class="list-group-item dashboard-list-group-item -code-lesson <% if code_lesson == @current_code_lesson %>-selected<% end %>" data-code-lesson-id="<%= code_lesson.id %>" data-class-id ="<%= @current_class.id %>">
              <%= code_lesson.name %>
            </li>
            <li class="list-group-item dashboard-list-group-item-info -code-lesson" <% unless code_lesson == @current_code_lesson %>style="display: none;"<% end %>>
              <div class="btn-group btn-group-sm">
                <%= link_to "View", code_lesson, class: 'btn btn-primary' %>
                <%= link_to "Insights", code_lesson_insights_path(code_lesson), class: 'btn btn-secondary' %>
              </div>
            </li>

          <% end %>
          <li class="list-group-item dashboard-list-group-item"><%= link_to 'Manage lessons', track_code_lessons_path(@current_track) %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-md-3" >
    <div class="card">
      <div class="card-header">
        Students
      </div>
      <ul class="list-group list-group-flush dashboard-list-group -students" style="overflow:scroll; height:300px;">
        <% if @current_class %>
          <% @current_class.students.each do |student| %>
          <div>
            <% if @current_code_lesson %>
              <% all_submissions = student.get_submissions(@current_code_lesson) %>
              <% most_recent = all_submissions.max_by(&:created_at) %>
              <% if !most_recent.nil? %>
                <% if most_recent.success %>
                  <li class="list-group-item dashboard-list-group-item -student <% if student == @current_student %>-selected<% end %>" data-student-id="<%= student.id %>">
                    <i class="fas fa-check"></i> <%= student.name %>
                    <button type="button" class="btn btn-info btn-sm float-sm-right" data-toggle="popover" data-trigger="focus" data-placement="right" title="Submissions & Hints" data-content="Number of submissions: <%= all_submissions.size %> </br>Hint used: <% if most_recent.used_hint %>'Yes <% else %> No <% end %>" data-html="true">Info</button>
                  </li>
                  <li class="list-group-item dashboard-list-group-item-info -student" <% unless student == @current_student %>style="display: none;"<% end %>>
                    <div class="btn-group btn-group-sm" role="group">
                      <%= link_to "Insight", student_insights_path(student), class: "btn btn-sm float-sm-left btn-secondary" %>
                      <%= link_to "Submissions", student_lesson_submissions_path(@current_code_lesson, student), class:"btn btn-sm float-sm-right btn-success" %>
                      <%= link_to "View", student, class: "btn btn-sm float-sm-left btn-secondary" %>
                    </div>
                  </li>
                <% else %>
                  <li class="list-group-item dashboard-list-group-item -student <% if student == @current_student %>-selected<% end %>" data-student-id="<%= student.id %>">
                    <i class="fas fa-times"></i> <%= student.name %>
                    <button type="button" class="btn btn-info btn-sm float-sm-right" data-toggle="popover" data-trigger="focus" data-placement="right" title="Submissions & Hints" data-content="Number of submissions: <%= all_submissions.length %> </br>Hint used: <% if most_recent.used_hint %>'Yes <% else %> No <% end %>" data-html="true">Info</button>
                  </li>
                  <li class="list-group-item dashboard-list-group-item-info -student" <% unless student == @current_student %>style="display: none;"<% end %>>
                    <div class="btn-group btn-group-sm" role="group">
                      <%= link_to "Insight", student_insights_path(student), class: "btn btn-sm float-sm-left btn-secondary" %>
                      <%= link_to "Submissions", student_lesson_submissions_path(@current_code_lesson, student), class:"btn btn-sm float-sm-right btn-success" %>
                      <%= link_to "View", student, class: "btn btn-sm float-sm-left btn-secondary" %>
                    </div>
                  </li>
                <% end %>
              <% else %>
                <li class="list-group-item dashboard-list-group-item -student <% if student == @current_student %>-selected<% end %>" data-student-id="<%= student.id %>">
                  <i class="fas fa-ellipsis-h"></i> <%= student.name %>
                </li>
                <li class="list-group-item dashboard-list-group-item-info -student" <% unless student == @current_student %>style="display: none;"<% end %>>
                  <div class="btn-group btn-group-sm" role="group">
                    <%= link_to "Insight", student_insights_path(student), class: "btn btn-sm float-sm-left btn-secondary" %>
                  </div>
                </li>
              <% end %>
            <% end %>
          </div>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<h2 class="text-center assignments-header">Current Assignments:</h2>

<div class="row">
  <div class="col-md-6">
    <% student_in_class = @current_class.students.first %>
    <% @current_class.outstanding_courses.each do |course| %>
      <% lesson_in_course = course.tracks.first.code_lessons.first %>
      <% assignment = lesson_in_course.get_assignment_for(student_in_class) %>
      <% if assignment != nil %>
        <div class="card">
          <div class="card-header">
            Assignment: <%= course.name %>
            <%= link_to "Cancel", cancel_assignment_path(assignment), class:"btn btn-sm float-sm-right btn-danger assignment-cancel-btn" %>
          </div>
          <div class="card-body">
            Date started: <%= assignment.date_start.strftime("%A %d-%b-%Y %H:%M:%S") %> </br>
            Date due: <%= assignment.date_due.strftime("%A %d-%b-%Y %H:%M:%S") %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>