config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  mount ActionCable.server => '/cable'

  get '/teacher-dashboard', to: 'dashboard#teacher', as: :teacher_dashboard
  get '/student-dashboard', to: 'dashboard#student', as: :student_dashboard

  get '/dashboard/change-class/:id', to: 'dashboard#change_class', as: :change_class
  get '/students/leaderboard', to: 'students#leaderboard', as: :students_leaderboard

  get '/assignments/:id/cancel', to: 'assignments#cancel', as: :cancel_assignment

  post '/dashboard/get-tracks', to: 'dashboard#get_tracks', as: :ajax_tracks
  post '/dashboard/get-code-lessons', to: 'dashboard#get_code_lessons', as: :ajax_code_lessons
  post '/dashboard/get-students', to: 'dashboard#get_students', as: :ajax_students

  get '/assignments/old-assignments/:id', to: 'assignments#old_assignments', as: :student_old_assignments

  get '/code-lessons/:code_lesson_id/submissions/:student_id', to: 'submissions#student_submissions', as: :student_lesson_submissions
  get 'submissions/:id', to: 'submissions#show', as: :submission

  get '/insights/course/:id', to: 'insights#course', as: :course_insights
  get '/insights/track/:id', to: 'insights#track', as: :track_insights
  get '/insights/student/:id', to: 'insights#student', as: :student_insights
  get '/insights/code_lesson/:id', to: 'insights#code_lesson', as: :code_lesson_insights
  post '/insights/get-course-submissions', to: 'insights#get_course_submissions', as: :ajax_course_submissions
  post '/insights/get-track-submissions', to: 'insights#get_track_submissions', as: :ajax_track_submissions
  post '/insights/get-code-lesson-submissions', to: 'insights#get_code_lesson_submissions', as: :ajax_code_lesson_submissions
  post '/insights/get-student-submissions', to: 'insights#get_student_submissions', as: :ajax_students_submissions
  post '/insights/get-student-time-spent', to: 'insights#get_student_time_spent', as: :ajax_students_time_spent


  resources :organisation_classes, path: 'classes'

  get '/classes/:id/courses', to: 'organisation_classes#courses', as: :organisation_class_courses
  post '/courses/:course_id/assign-to-classes', to: 'courses#assign_to_classes', as: :assign_course_to_classes

  resources :courses, shallow: true do
    resources :tracks do
      resources :code_lessons, path: 'code-lessons' do
        resources :submissions
      end
    end
  end

  post '/code-lessons/:id/run-code', to: 'code_lessons#run_code', as: :run_code
  post '/code-lessons/:id/get-hint', to: 'code_lessons#get_hint', as: :get_hint
  post '/code-lessons/:id/get-starting-code', to: 'code_lessons#get_starting_code', as: :get_starting_code
  post '/code-lessons/:id/get-next-lesson', to: 'code_lessons#get_next_lesson', as: :get_next_lesson
  get '/code-lessons/:code_lesson_id/chat/:chat_id', to: 'code_lessons#chat', as: :code_lesson_chat

  get '/library', to: 'course_templates#index', as: :course_templates
  post '/library', to: 'course_templates#create'
  post '/course-templates/:course_template_id/add-to-organisation', to: 'course_templates#add_to_organisation', as: :add_course_template_to_organisation

  resources :course_templates, path: 'course-templates', shallow: true, except: :index do
    resources :track_templates, path: 'track-templates' do
      resources :code_lesson_templates, path: 'code-lesson-templates'
    end
  end

  resources :chat_messages do
    resources :chats
  end

  resources :live_coding_sessions, path: 'live-coding-sessions'
  get '/live-coding-sessions/:id/resolve', to: 'live_coding_sessions#resolve', as: :resolve_live_coding_session
  post '/live-coding-sessions/:live_coding_session_id/publish-code', to: 'live_coding_sessions#publish_code', as: :live_coding_session_publish_code

  get '/students/:id/get-assignments', to: 'students#get_assignments', as: :student_get_assignments

  get '/students/new', to: 'students#new', as: :new_student
  post '/students', to: 'students#create'

  devise_for :admins, skip: [:registrations]
  devise_for :teachers
  devise_for :students
  resources :students, only: [:index, :show, :edit, :destroy, :update]

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :students_classes
  has_many :organisation_classes, class_name: 'OrganisationClass', through: :students_classes
  has_many :assignments
  has_many :chat_messages, as: :messagable
  belongs_to :organisation

  validates :first_name,   presence: true
  validates :last_name,    presence: true
  validates :organisation, presence: true

  def name
    "#{first_name} #{last_name}"
  end

  def get_tracks_assignments
    assignments = outstanding_assignments({ created_at: :asc })
    tracks = []
    assignments.each do |a|
      track = a.code_lesson.track
      if !tracks.include?(track)
        tracks << track
      end
    end
    return tracks
  end

  def outstanding_assignments(order = { date_due: :asc })
    @assignments = Assignment.where(
      "student_id = ? AND date_start < ? AND date_due > ?",
      id, Time.now, Time.now
    ).order(order)

    # @assignments.select do |assignment|
    #   !has_completed?(assignment.code_lesson)
    # end
    return @assignments
  end

  def old_assignments(order = {date_due: :desc})
    @assignments = Assignment.where("student_id = ? AND date_due < ?", id, Time.now).order(order)
  end

  def old_courses()
    @old_assignments = old_assignments
    @old_courses = []
    @assignments.each do |a|
      code_lesson = a.code_lesson
      track = code_lesson.track
      course = track.course
      if !@old_courses.include?(course)
        @old_courses << course
      end
    end
    return @old_courses
  end

  def outstanding_courses()
    @assignments = outstanding_assignments
    @courses = []
    @assignments.each do |a|
      code_lesson = a.code_lesson
      track = code_lesson.track
      course = track.course
      if !@courses.include?(course)
        @courses << course
      end
    end
    return @courses
  end


  def has_completed?(code_lesson)
    Submission.where(student_id: id, code_lesson_id: code_lesson.id, success: true).any?
  end

  def get_submissions(code_lesson)
    Submission.where(student_id: id, code_lesson_id: code_lesson.id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_teacher!, only: :index

  def index
  end

  def get_assignments
    student = Student.find(params[:id])
    assignments = student.outstanding_assignments({ created_at: :asc })
    return_obj = {
      assignments: assignments,
      notification_message: "You have a new assignment, go to your student dashboard to view it!"
    }
    render json: return_obj.to_json
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      params[:student][:organisation_classes].each do |c|
        if c
          StudentsClass.create(student_id: @student.id, organisation_class_id: c)
        end
      end
      return redirect_to(students_path)
    else
      render :new

    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to(students_path)
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      if student_signed_in?
        return redirect_to(student_dashboard_path)
      end
      return redirect_to(student_path)
    end
  end



  private
  def student_params
    params.require(:student).permit(:first_name, :last_name, :password, :password_confirmation, :organisation_id, :email)
  end
end

app/views/students/edit.html.erb
<%= form_with(model: @student, local: true) do |form| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :first_name %><br/>
    <%= form.text_field :first_name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= form.label :last_name %><br />
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= form.label :email %><br />
    <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="actions row">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/students/index.html.erb
<h1 class="display-4 row">All students</h1>

<table id="student_table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Actions</th>
  </tr>
  </thead>
    <% current_teacher.organisation.students.each do |s| %>
      <tbody>
        <td><%= s.name %></td>
        <td><%= s.email %></td>
        <td>
          <%= link_to "View", s,class: "btn btn-primary" %>
          <%= link_to "Edit", edit_student_path(s), class: "btn btn-primary"%>
          <%= link_to "Delete", student_path(s), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"%>
        </td>
      </tbody>
    <% end %>
    <td><%= link_to "Add Student", new_student_path, class: "btn btn-primary" %></td>
    <td> </td>
    <td> </td>
</table>

app/views/students/leaderboard.html.erb
<h1 class="display-4">Leaderboard</h1>
<p>Every code lesson completed will score 10 points</p>
<p>Every track completed will score 30 points</p>
<p>Every course completed will score 50 points</p>
<table id="student_leaderboard">
  <thead>
  <tr>
    <th>Name</th>
    <th>Points</th>
  </tr>
  </thead>
  <tbody>
    <% if teacher_signed_in? %>
      <% current_user = current_teacher %>
    <% else %>
      <% current_user = current_student %>
    <% end %>
    <% current_user.organisation.students.each do |s| %>
      <tr>
        <td><%= s.name %></td>
        <td><%= s.points %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<% if !teacher_signed_in? %>
  <h2 class="display-4 row">Sign up</h2>
<% else %>
  <h2 class="display-4 row">Sign up student</h2>
<% end %>

<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= f.label :password %>
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= f.label :organisation_classes %><br />
    <%= f.collection_check_boxes :organisation_classes, current_teacher.organisation_classes, :id, :name , class: "form-check" %>
  </div>

  <div class="form-group row">
    <%= f.hidden_field :organisation_id, value: current_teacher.organisation_id%>
  </div>


  <div class="form-group row">
    <%= f.submit "Sign up", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/students/show.html.erb
<h1 class="display-4"><%= @student.name %> Profile:</h1>
</br>

<h3>Badges:</h3>
<div>
  <% rand_num_badge = 1 + rand(6) %>
  <% rand_num_badge.times do |i| %>
    <% rand_badge = 1 + rand(6) %>
    <%= image_tag "#{rand_badge}.png" %>
  <% end %>
</div>