config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  mount ActionCable.server => '/cable'

  get '/teacher-dashboard', to: 'dashboard#teacher', as: :teacher_dashboard
  get '/student-dashboard', to: 'dashboard#student', as: :student_dashboard

  get '/dashboard/change-class/:id', to: 'dashboard#change_class', as: :change_class
  get '/students/leaderboard', to: 'students#leaderboard', as: :students_leaderboard

  get '/assignments/:id/cancel', to: 'assignments#cancel', as: :cancel_assignment

  post '/dashboard/get-tracks', to: 'dashboard#get_tracks', as: :ajax_tracks
  post '/dashboard/get-code-lessons', to: 'dashboard#get_code_lessons', as: :ajax_code_lessons
  post '/dashboard/get-students', to: 'dashboard#get_students', as: :ajax_students

  get '/assignments/old-assignments/:id', to: 'assignments#old_assignments', as: :student_old_assignments

  get '/code-lessons/:code_lesson_id/submissions/:student_id', to: 'submissions#student_submissions', as: :student_lesson_submissions
  get 'submissions/:id', to: 'submissions#show', as: :submission

  get '/insights/course/:id', to: 'insights#course', as: :course_insights
  get '/insights/track/:id', to: 'insights#track', as: :track_insights
  get '/insights/student/:id', to: 'insights#student', as: :student_insights
  get '/insights/code_lesson/:id', to: 'insights#code_lesson', as: :code_lesson_insights
  post '/insights/get-course-submissions', to: 'insights#get_course_submissions', as: :ajax_course_submissions
  post '/insights/get-track-submissions', to: 'insights#get_track_submissions', as: :ajax_track_submissions
  post '/insights/get-code-lesson-submissions', to: 'insights#get_code_lesson_submissions', as: :ajax_code_lesson_submissions
  post '/insights/get-student-submissions', to: 'insights#get_student_submissions', as: :ajax_students_submissions
  post '/insights/get-student-time-spent', to: 'insights#get_student_time_spent', as: :ajax_students_time_spent


  resources :organisation_classes, path: 'classes'

  get '/classes/:id/courses', to: 'organisation_classes#courses', as: :organisation_class_courses
  post '/courses/:course_id/assign-to-classes', to: 'courses#assign_to_classes', as: :assign_course_to_classes

  resources :courses, shallow: true do
    resources :tracks do
      resources :code_lessons, path: 'code-lessons' do
        resources :submissions
      end
    end
  end

  post '/code-lessons/:id/run-code', to: 'code_lessons#run_code', as: :run_code
  post '/code-lessons/:id/get-hint', to: 'code_lessons#get_hint', as: :get_hint
  post '/code-lessons/:id/get-starting-code', to: 'code_lessons#get_starting_code', as: :get_starting_code
  post '/code-lessons/:id/get-next-lesson', to: 'code_lessons#get_next_lesson', as: :get_next_lesson
  get '/code-lessons/:code_lesson_id/chat/:chat_id', to: 'code_lessons#chat', as: :code_lesson_chat

  get '/library', to: 'course_templates#index', as: :course_templates
  post '/library', to: 'course_templates#create'
  post '/course-templates/:course_template_id/add-to-organisation', to: 'course_templates#add_to_organisation', as: :add_course_template_to_organisation

  resources :course_templates, path: 'course-templates', shallow: true, except: :index do
    resources :track_templates, path: 'track-templates' do
      resources :code_lesson_templates, path: 'code-lesson-templates'
    end
  end

  resources :chat_messages do
    resources :chats
  end

  resources :live_coding_sessions, path: 'live-coding-sessions'
  get '/live-coding-sessions/:id/resolve', to: 'live_coding_sessions#resolve', as: :resolve_live_coding_session
  post '/live-coding-sessions/:live_coding_session_id/publish-code', to: 'live_coding_sessions#publish_code', as: :live_coding_session_publish_code

  get '/students/:id/get-assignments', to: 'students#get_assignments', as: :student_get_assignments

  get '/students/new', to: 'students#new', as: :new_student
  post '/students', to: 'students#create'

  devise_for :admins, skip: [:registrations]
  devise_for :teachers
  devise_for :students
  resources :students, only: [:index, :show, :edit, :destroy, :update]

end

app/models/track_template.rb
class TrackTemplate < ApplicationRecord
  belongs_to :course_template
  has_many :code_lesson_templates, dependent: :destroy

  validates :name,            presence: true
  validates :order,           presence: true
  validates :course_template, presence: true
end

app/controllers/track_templates_controller.rb
class TrackTemplatesController < ApplicationController
  before_action :set_track_template, only: [:show, :edit, :update, :destroy]

  # GET /track_templates
  # GET /track_templates.json
  def index
    @track_templates = TrackTemplate.all
  end

  # GET /track_templates/1
  # GET /track_templates/1.json
  def show
  end

  # GET /track_templates/new
  def new
    @track_template = TrackTemplate.new
  end

  # GET /track_templates/1/edit
  def edit
  end

  # POST /track_templates
  # POST /track_templates.json
  def create
    @track_template = TrackTemplate.new(track_template_params)

    respond_to do |format|
      if @track_template.save
        format.html { redirect_to @track_template, notice: 'Track template was successfully created.' }
        format.json { render :show, status: :created, location: @track_template }
      else
        format.html { render :new }
        format.json { render json: @track_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /track_templates/1
  # PATCH/PUT /track_templates/1.json
  def update
    respond_to do |format|
      if @track_template.update(track_template_params)
        format.html { redirect_to @track_template, notice: 'Track template was successfully updated.' }
        format.json { render :show, status: :ok, location: @track_template }
      else
        format.html { render :edit }
        format.json { render json: @track_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /track_templates/1
  # DELETE /track_templates/1.json
  def destroy
    @track_template.destroy
    respond_to do |format|
      format.html { redirect_to track_templates_url, notice: 'Track template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track_template
      @track_template = TrackTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_template_params
      params.require(:track_template).permit(:name, :order, :course_id, :description)
    end
end

app/helpers/track_templates_helper.rb
module TrackTemplatesHelper
end

app/views/track_templates/_form.html.erb
<%= form_with(model: track_template, local: true) do |form| %>
  <% if track_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track_template.errors.count, "error") %> prohibited this track_template from being saved:</h2>

      <ul>
      <% track_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/track_templates/edit.html.erb
<h1>Editing Track Template</h1>

<%= render 'form', track_template: @track_template %>

<%= link_to 'Show', @track_template %> |
<%= link_to 'Back', track_templates_path %>

app/views/track_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Track Templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Order</th>
      <th>Course</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @track_templates.each do |track_template| %>
      <tr>
        <td><%= track_template.name %></td>
        <td><%= track_template.order %></td>
        <td><%= track_template.course_id %></td>
        <td><%= track_template.description %></td>
        <td><%= link_to 'Show', track_template %></td>
        <td><%= link_to 'Edit', edit_track_template_path(track_template) %></td>
        <td><%= link_to 'Destroy', track_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track Template', new_track_template_path %>

app/views/track_templates/new.html.erb
<h1>New Track Template</h1>

<%= render 'form', track_template: @track_template %>

<%= link_to 'Back', track_templates_path %>

app/views/track_templates/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <div class="card text-center">
      <div class="card-header">
        <%= @track_template.name %>
      </div>
      <div class="card-body">
        <%= @track_template.description %>
      </div>
      <div class="card-footer text-muted">
        <%= pluralize(@track_template.code_lesson_templates.length, 'Code Lesson') %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <ul class="list-group">
      <% @track_template.code_lesson_templates.each do |lesson| %>
        <li class="list-group-item">
          <div class="float-right"><%= lesson.language.name %></div>
          <%= link_to lesson.name, lesson %>
        </li>
      <% end %>
    </ul>
  </div>
</div>